### ISSUE TITLE
Integrate with Swift without keystone

### ISSUE THREAD

**Issue by Yuav** [rackspace/php-opencloud#406]
Equivalent of:

curl -i -H "X-Auth-User: test:tester" -H "X-Auth-Key: asdf"  http://127.0.0.1:8080/auth/v1.0/

To make use of the temporary users [filter:tempauth] in proxy-users.conf

**Comment by ypollart** [comment]
Hello,

We have developed a small solution in order to use Swift+Tempauth with php-opencloud and we've just pushed it to github and packagist: https://github.com/fia-net/openstack-tempauth 

It's far from being the perfect solution but it shows that it can be done with a very small amount of code. 

It may help people using tempauth while waiting for an official upgrade!

Regards,
Yannick.

**Comment by jamiehannaford** [comment]
We will not be implementing this, Keystone is the recommended auth mechanism for OpenStack.
