### ISSUE TITLE
Not possible to set metadata and HTTP headers together for Swift resources

### ISSUE THREAD

**Issue by jamiehannaford** [rackspace/php-opencloud#641]
To set HTTP headers on a Swift resource, you run:

``` php
$this->saveMetadata(['foo' => 'bar'], false);
```

And metadata like so:

``` php
$this->saveMetadata(['foo' => 'bar']);
```

which means they're mutually exclusive. This should not be the case.

**Comment by PatrickRose** [comment]
Since it's a feature I'm going to need I can work on a PR?

**Comment by jamiehannaford** [comment]
@PatrickRose Now that I think about it, you could do something like this:

```php
$headers = ['X-Custom-Header' => 'foo'];
$metadata = $thing::stockHeaders([
   'key1' => 'val1',
   'key2' => 'val2',
]);

$thing->saveMetadata($headers + $metadata, false);
```

where `$thing` is either account, container or object. Does that work for you?

**Comment by PatrickRose** [comment]
It does work - but it's also asking for trouble in my opinion. All that has to happen is someone to forget to do that in one place and suddenly they've lost all their metadata/custom headers.

Any custom header that a resource supports should be supported by the API imo with a get/set method. Any other custom headers a developer wants to use, that's their concern ;-)

**Comment by jamiehannaford** [comment]
I'm not sure individual setters would be a good idea - I think it would unnecessarily bloat the interface. I definitely agree that the current solution and code is sub-optimal, though.

FWIW, I'm working on a new [v2 OpenStack SDK](https://github.com/php-opencloud/openstack) which should have a much cleaner interface for doing these things. If you'd like to check that out and provide feedback (or even better, PRs) I'd appreciate it.

Because of v2 development, I've very reluctant to add major new functionality to v1. If we wanted to change the interface, we'd have to do it in v2 anyway due to semantic versioning.

**Comment by PatrickRose** [comment]
> I'm not sure individual setters would be a good idea - I think it would unnecessarily bloat the interface

Hmm, I agree. The only other solution would be to add those as exceptions wherever metadata is set, and that seems worse.

> FWIW, I'm working on a new v2 OpenStack SDK which should have a much cleaner interface for doing these things. If you'd like to check that out and provide feedback (or even better, PRs) I'd appreciate it.

Sadly I'm stuck on 5.4 for a while (as part of the project we'll be moving to 5.6) but I'm not sure what the internal timescale is so I'd rather stick with v1 for now. As I previously mentioned - for my purposes I can probably get away with using the `setMetadata($data, false)` trick since I don't think I'll need Swift metadata.

**Comment by PatrickRose** [comment]
> I'm not sure individual setters would be a good idea - I think it would unnecessarily bloat the interface. I definitely agree that the current solution and code is sub-optimal, though.

Is it possible to revisit this? I keep getting bit by this a lot at the moment. If I want to get the `X-Delete-At` header I have to revert to using guzzle which is a really hacky way of doing things. `X-Delete-At` is mentioned in the API documentation as system metadata, so it seems to me that I should be able to get/set it as I could Content-Type, Last-Modified etc.

**EDIT**: I think the general ticket where random headers are lost isn't something the API should handle because a) That'd be complicated and b) Metadata headers are probably a better fit anyway. `X-Delete-At` is just annoyingly special and it's difficult to interact with it with this API.
