### ISSUE TITLE
Library Missing 'X-Delete-After' Capability

### ISSUE THREAD

**Issue by thejollyrogerx** [rackspace/php-opencloud#68]
I parsed through most the libraries looking for this. I couldn't find this directive available. We need to integrate this in to the library.

Sincerely,
Sean

**Comment by takanomi** [comment]
I can find no way to add the 'X-Delete-After' header to a file with the current library, and this suggested solution is no longer supported.

The furthest I got was the following after doing the initial uploadObject() (setting it as metadata for the upload has no effect), it wouldn't work at all unless you went through getPartialObject():

    $obj = $container->getPartialObject( $filename );
    $obj->saveMetadata( array( 'Content-Type' => 'text/plain', 'X-Delete-After' => '86400' ), false );

But this wouldn't actually save it, I had to call:

    $obj->update();

And, while it set the X-Delete-After header correctly on the file, it would generate a fatal Guzzle\Http\Exception\ServerErrorResponseException. Catching the exception stopped the update() from working at all for some reason.

Any ideas on how to achieve this with the library?

Thanks
Steve

**Comment by jamiehannaford** [comment]
@takanomi hmm, when I run:

```php
$obj->saveMetadata([
  'Content-Type' => 'text/plain',
  'X-Delete-After' => '86400'
], false);
```
_without_ the `update()`, it successfully saves both the `Content-Type` and `X-Delete-After` headers. Would you mind [enabling the log plugin](https://gist.github.com/jamiehannaford/8469989) and then send the results to jamie.hannaford@rackspace.com, please? (Note: it will output all HTTP transactions over STDOUT, so make sure to do this in a dev environment).

**Comment by PatrickRose** [comment]
@jamiehannaford - I've just run this now and saving the X-Delete-After in the metadata doesn't work as intended. That will then send a  `X-Object-Meta-X-Delete-After: 30` header instead of a `X-Delete-After: 30` header meaning that the next GET request for the object doesn't receive a `X-Delete-At: 1445422707` header.

**Comment by jamiehannaford** [comment]
@PatrickRose Did you specify `false` as the second argument? If so, a PR would definitely be welcome. thanks!

**Comment by PatrickRose** [comment]
Ah, didn't spot the `false`. My bad!

**Comment by PatrickRose** [comment]
Just had a bit more of a play, and I think this isn't a good solution. For my purposes it'll work fine, but for others it won't.

```php
$object->saveMetadata(['Metadata' => 'value'], true);
var_dump($object->retrieveMetadata());
//class OpenCloud\Common\Metadata#47 (4) {
//  protected $metadata =>
//  array(1) {
//    'metadata' =>
//    string(5) "value"
//  }
//  private $properties =>
//  array(0) {
//  }
//  private $logger =>
//  NULL
//  protected $aliases =>
//  array(0) {
//  }
//}

$object->saveMetadata(['X-Delete-After' => 86400], false);
var_dump($object->retrieveMetadata());
//class OpenCloud\Common\Metadata#52 (4) {
//  protected $metadata =>
//  array(0) {
//  }
//  private $properties =>
//  array(0) {
//  }
//  private $logger =>
//  NULL
//  protected $aliases =>
//  array(0) {
//  }
//}
```

Inspecting the requests tells me that the `X-Delete-At` header was returned but I lost the `Metadata=Value` keypair. That's to be expected - but then I can't really use appendMetadata because it won't set the header prefix for those fields unless I use stockHeaders. *But then* if I update the metadata for some reason but want to keep the same expiration date (I can't think of a use case at the moment, but someone will have one) that'll get lost forever since there's no way to receive it from the file.

**Comment by jamiehannaford** [comment]
@PatrickRose Yeah, you're completely right. I've opened #641 to capture this bug. Thanks for reporting
