### ISSUE TITLE
Calling setToken() / authenticate() / getToken() returns a new token ID.

### ISSUE THREAD

**Issue by kreeves** [rackspace/php-opencloud#681]
I'm trying to determine how this client code should behave. We're attempting to generate a valid token, and then re-use it between requests in PHP. The only way I can see to do this is with the code below. However, it appears that I'm still getting a new token with each call to "authenticate()"

```
$client = new Rackspace($config['endpoint'], [
    'username' => $config['username'], 'apiKey' => $config['key'],
]);

// I ran this code once with this line commented out so that I could get a valid token to put in here.
$client->setToken('A VALID TOKEN');

$client->authenticate();

print $client->getToken();
```

Is this the intended behavior? Is there a different way I should be providing the $client with the valid token?

**Comment by jamiehannaford** [comment]
The `authenticate` method will always generate a token, that's its point: it performs a POST request to the identity API and gets back a catalog with a token embedded. 

Here are some docs about how to cache credentials: http://docs.php-opencloud.com/en/latest/caching-creds.html. Is this what you're looking to do? 

By default the SDK does not store credentials because it makes no assumptions about the storage medium (local filesystem, Redis, memcached, MySQL, etc.) - that's a decision best left to the end-user in my opinion.

**Comment by kreeves** [comment]
Thank you @jamiehannaford , I think this is just what I was looking for!
