### ISSUE TITLE
Token not expired, but randomly getting 401 Unauthorized errors?

### ISSUE THREAD

**Issue by georaldc** [rackspace/php-opencloud#708]
Don't know if this is the right repo to post this issue/question, but what would cause API access to suddenly stop working with a valid token? I currently use the php SDK to upload files to Cloud Storage and while this has worked fine for a while now using code similar to http://php-opencloud.readthedocs.io/en/latest/caching-creds.html to cache tokens locally, this all of a sudden stopped being effective since my tokens would just stop working randomly, despite not being expired and only being an hour old (I tested the problematic tokens on postman and sure enough, they wouldn't let me through).

Would going over rate limits invalidate tokens server side? That's all I could think of at the moment, but I always thought that would just slow down requests.

**Comment by PatrickRose** [comment]
Tokens from keystone only last one hour by default so you might need to do
some configuration.

On 27 Apr 2017 01:54, "Georald Camposano" <notifications@github.com> wrote:

Don't know if this is the right repo to post this issue/question, but what
would cause API access to suddenly stop working with a valid token? I
currently use the php SDK to upload files to Cloud Storage and while this
has worked fine for a while now using code similar to http://php-opencloud.
readthedocs.io/en/latest/caching-creds.html to cache tokens locally, this
all of a sudden stopped being effective since my tokens would just stop
working randomly, despite not being expired and only being an hour old (I
tested the problematic tokens on postman and sure enough, they wouldn't let
me through).

Would going over rate limits invalidate tokens server side? That's all I
could think of at the moment, but I always thought that would just slow
down requests.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/rackspace/php-opencloud/issues/708>, or mute the thread

**Comment by georaldc** [comment]
I thought they were valid for 24 hours? Also, I noticed that the tokens start working again after a while.

**Comment by georaldc** [comment]
So I’m starting to have this problem again but more frequently this time. I use a queue to move uploaded files from our web server to Cloud Storage and API access would just stop working with 401 errors. This again is with unexpired tokens too so my code isn’t getting the chance to refresh them. If I retry my failed queue jobs though after waiting a while (and with the same cached token), they start to go through again.

Am I hitting some sort of access rate limitation here and my tokens are temporarily being made unusable?

**Comment by lcjury** [comment]
I'm moving our file storage to Rackspace cloud files and we're having the same issue, randomly, sometimes I upload a file and get a 401 error (Unauthorized), but if I try again, everything works as expected.

**Comment by georaldcamposano** [comment]
I spoke to Rackspace support a few weeks ago about the authentication issues. They said that this was an ongoing issue on their end that they were working on to resolve

**Comment by georaldc** [comment]
I spoke to Rackspace support a few weeks ago about the authentication issues. They said that this was an ongoing issue on their end that they were working on to resolve, so this is probably more of an internal issue there

**Comment by lcjury** [comment]
@georaldc Have you done something to survive until they solve this issue?. I have some code who just fails and leave tasks without ending because of this.

**Comment by georaldc** [comment]
@lcjury fortunately for me, most of my code that interacts with rackspace live as jobs managed by beanstalkd and are not exactly time-critical so ones that fail either stay buried or get retried automatically
